fix(ci): add snyk debug bash script

diff --git a/.github/workflows/snyk-scan.yaml b/.github/workflows/snyk-scan.yaml
--- a/.github/workflows/snyk-scan.yaml
+++ b/.github/workflows/snyk-scan.yaml
@@ -26,9 +26,16 @@ jobs:
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
         run: |
+          snyk auth ${SNYK_TOKEN}
+
           snyk test --all-projects \
+                    --command=cargo \
                     --severity-threshold=high \
-                    --sarif-file-output=snyk.sarif || true
+                    --sarif-file-output=snyk.sarif || echo "Snyk found issues or failed, continuing to upload report..."
+
+          if [ ! -f snyk.sarif ]; then
+            echo "SARIF file was not generated. Creating a dummy empty SARIF."
+            echo '{"$schema":"https://json.schemastore.org/sarif-2.1.0-rtm.5.json","version":"2.1.0","runs":[]}' > snyk.sarif
 
       - name: Upload result to GitHub Code Scanning
         uses: github/codeql-action/upload-sarif@v4
